version: '3.8'

services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=Ä‘uociku.5mildollar2026.xyz
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://duociku.5mildollar2026.xyz/
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
    volumes:
      - ./data:/home/node/.n8n
    labels:
      - "coolify.enabled=true"
      - "coolify.domain=duociku.5mildollar2026.xyz"
